practice2/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/',include('common.urls')),
    path('', base_views.index,name='index'),
]

practice2/pybo/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views, comment_views



app_name = 'pybo'

urlpatterns=[
  # base
  path('', base_views.index,name='index'),
  path('<int:question_id>/',base_views.detail,name='detail'),

# question
  path('question/create/', question_views.question_create, name='question_create'),
  path('question/modify/<int:question_id>/',question_views.question_modify, name='question_modify'),
  path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
  
# answer
  path('answer/create/<int:question_id>/',answer_views.answer_create, name='answer_create'),
  path('answer/modify/<int:answer_id>/', answer_views.answer_modify,   name='answer_modify'),
  path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

# comment
  path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
  path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
  path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
  path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
  path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
  path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),



]

practice2/pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
  author = models.ForeignKey(User, on_delete = models.CASCADE , null=True)
  subject = models.CharField(max_length=200)
  content = models.TextField()
  create_date = models.DateTimeField()
  modify_date = models.DateTimeField(null=True, blank = True)

  def __str__(self):
    return self.subject

class Answer(models.Model):
  author = models.ForeignKey(User, on_delete = models.CASCADE , null=True)
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  content = models.TextField()
  create_date = models.DateTimeField()
  modify_date = models.DateTimeField(null=True, blank = True)


  def __str__(self):
    return self.subject
  
class Comment(models.Model):
  author = models.ForeignKey(User,on_delete=models.CASCADE)
  content = models.TextField()
  create_date = models.DateTimeField()
  modify_date = models.DateTimeField(null=True, blank = True)
  question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
  answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

  

practice2/pybo/forms.py
from django import forms
from pybo.models import Answer, Question, Comment

class QuestionForm(forms.ModelForm):
  class Meta:
    model = Question
    fields = ['subject', 'content']

    widgets = { 'subject': forms.TextInput(attrs={'class': 'form-control'}), 'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),}
    labels = {
    'subject': '제목',
    'content': '내용',
    }

class AnswerForm(forms.ModelForm):
  class Meta:
    model=Answer
    fields = ['content']
    lables = {
      'content':'답변내용'
    }

class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ['content']
    labels = {
    'content': '댓글내용',
    }

practice2/pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import CommentForm, AnswerForm
from ..models import Question, Answer, Comment



@login_required(login_url = 'common:login')
def answer_create(request, question_id):
  """
  pybo 답변등록
  """
  question = get_object_or_404(Question, pk=question_id)
  if request.method == "POST":
    form = AnswerForm(request.POST)
    if form.is_valid():
      answer = form.save(commit=False)
      answer.author = request.user
      answer.create_date = timezone.now()
      answer.question = question
      answer.save()
      return redirect('pybo:detail', question_id=question.id)
  else:
    form = AnswerForm()
  context = {'question': question, 'form': form}
  return render(request, 'pybo/question_detail.html', context)



@login_required(login_url='common:login')
def answer_modify(request, answer_id):
  """
  pybo 답변수정
  """
  answer = get_object_or_404(Answer, pk=answer_id)
  if request.user != answer.author:
    messages.error(request, '수정권한이 없습니다')
    return redirect('pybo:detail', question_id=answer.question.id)
  if request.method == "POST":
    form = AnswerForm(request.POST, instance=answer)
    if form.is_valid():
      answer = form.save(commit=False)
      answer.author = request.user
      answer.modify_date = timezone.now()
      answer.save()
      return redirect('pybo:detail', question_id=answer.question.id)
  else:
    form = AnswerForm(instance=answer)
  context = {'answer': answer, 'form': form}
  return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
  """
  pybo 답변삭제
  """
  answer = get_object_or_404(Answer, pk=answer_id)
  if request.user != answer.author:
    messages.error(request, '삭제권한이 없습니다')
  else:
    answer.delete()
  return redirect('pybo:detail', question_id=answer.question.id)

practice2/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question


def index(request):
  """
  pybo 목록 출력
  """

  page = request.GET.get('page','1') 
  question_list = Question.objects.order_by('-create_date')
  paginator = Paginator(question_list,10)
  page_obj = paginator.get_page(page)
  context = {'question_list':page_obj}

  # question_list = Question.objects.order_by('-create_date')
  # context= {'question_list':question_list}

  return render(request, 'pybo/question_list.html',context)

def detail(request, question_id):
  """
  pybo 내용 출력
  """
  # question=Question.objects.get(id=question_id)
  question=get_object_or_404(Question,pk=question_id)
  context = {'question':question}
  return render(request,'pybo/question_detail.html',context)

practice2/pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from ..forms import CommentForm
from ..models import Question, Answer, Comment


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  if request.method == "POST":
    form = CommentForm(request.POST)
    if form.is_valid():
      comment = form.save(commit=False)
      comment.author = request.user
      comment.create_date = timezone.now()
      comment.question = question
      comment.save()
      return redirect('pybo:detail', question_id=question.id)
  else:
    form = CommentForm()
  context = {'form': form}
  return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
  """
  pybo 질문댓글수정
  """
  comment = get_object_or_404(Comment, pk=comment_id)
  if request.user != comment.author:
    messages.error(request, '댓글수정권한이 없습니다')
    return redirect('pybo:detail', question_id=comment.question.id)

  if request.method == "POST":
    form = CommentForm(request.POST, instance=comment)
    if form.is_valid():
      comment = form.save(commit=False)
      comment.author = request.user
      comment.modify_date = timezone.now()
      comment.save()
      return redirect('pybo:detail', question_id=comment.question.id)
  else:
    form = CommentForm(instance=comment)
  context = {'form': form}
  return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
  """
  pybo 질문댓글삭제
  """
  comment = get_object_or_404(Comment, pk=comment_id)
  if request.user != comment.author:
    messages.error(request, '댓글삭제권한이 없습니다')
    return redirect('pybo:detail', question_id=comment.question.id)
  else:
    comment.delete()
  return redirect('pybo:detail', question_id=comment.question.id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
  """ pybo 답글댓글등록 """
  answer = get_object_or_404(Answer, pk=answer_id)
  if request.method == "POST":
    form = CommentForm(request.POST)
    if form.is_valid():
      comment = form.save(commit=False)
      comment.author = request.user
      comment.create_date = timezone.now()
      comment.answer = answer
      comment.save()
      return redirect('pybo:detail',  question_id=comment.answer.question.id)
  else:
    form = CommentForm()
  context = {'form': form}
  return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
  """ pybo 답글댓글수정 """
  comment = get_object_or_404(Comment, pk=comment_id)
  if request.user != comment.author:
    messages.error(request, '댓글수정권한이 없습니다')
    return redirect('pybo:detail', question_id=comment.answer.question.id)
  if request.method == "POST":
    form = CommentForm(request.POST, instance=comment)
    if form.is_valid():
      comment = form.save(commit=False)
      comment.author = request.user
      comment.modify_date = timezone.now()
      comment.save()
      return redirect('pybo:detail',  question_id=comment.answer.question.id)
  else:
    form = CommentForm(instance=comment)
  context = {'form': form}
  return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
  """
  pybo 답글댓글삭제
  """
  comment = get_object_or_404(Comment, pk=comment_id)
  if request.user != comment.author:
    messages.error(request, '댓글삭제권한이 없습니다')
    return redirect('pybo:detail', question_id=comment.answer.question.id)
  else:
    comment.delete()
  return redirect('pybo:detail', question_id=comment.answer.question.id)

practice2/pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
  """
  pybo 질문등록
  """
  if request.method == 'POST':
    form = QuestionForm(request.POST)
    if form.is_valid():
      question = form.save(commit=False)
      print('---------------------')
      print(request.user)
      question.author = request.user
      question.create_date = timezone.now()
      question.save()
      return redirect('pybo:index')
  else:
    form = QuestionForm()
  context = {'form': form}
  return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
  """
  질문수정
  """
  question = get_object_or_404(Question, pk=question_id)
  if request.user != question.author:
    messages.error(request, '수정권한이 없습니다.')
    return redirect('pybo:detail', question_id=question.id)
  if request.method == "POST":
    # 질문 수정을 위해 값 덮어쓰기
    form = QuestionForm(request.POST, instance=question)
    if form.is_valid():
      question = form.save(commit=False)
      question.author = request.user
      question.modify_date = timezone.now() # 수정일시 저장
      question.save()
      return redirect('pybo:detail', question_id=question.id)
  else:
    # 질문 수정 화면에 기존 제목, 내용 반영
    form = QuestionForm(instance=question)
  context = {'form': form}
  return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
  """
  pybo 질문삭제
  """
  question = get_object_or_404(Question, pk=question_id)
  if request.user != question.author:
    messages.error(request, '삭제권한이 없습니다')
    return redirect('pybo:detail', question_id=question.id)
  question.delete()
  return redirect('pybo:index')

practice2/templates/pybo/answer_form.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <form method="post" class="post-form">
    {% csrf_token %} {% include "error/form_error.html" %}
    <div class="form-group">
      <label for="content">답변내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> 저장하기</button>
    <a href="javascript:history.back()" class="btn btn-primary"><i class="fas fa-undo"></i> 돌아가기</a>
  </form>
</div>
{% endblock %}

practice2/templates/pybo/comment_form.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <h5 class="border-bottom pb-2">댓글등록하기</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %} {% include "error/form_error.html" %}
    <div class="form-group">
      <label for="content">댓글내용</label>
      <textarea class="form-control" name="content" id="content" rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

practice2/templates/pybo/comment_list.html
<!-- 질문댓글 -->
{% if question.comment_set.count > 0 %}
<div class="mt-3">
  {% for comment in question.comment_set.all %}
  <div class="comment py-2 text-muted">
    <span style="white-space: pre-line">{{ comment.content }}</span>
    <span>
      - {{ comment.author }}, {{ comment.create_date }} {% if comment.modify_date %} (수정:{{ comment.modify_date }}) {% endif %}
    </span>
    {% if request.user == comment.author %}
    <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>,
    <a href="#" class="small delete" data-url="{% url 'pybo:comment_delete_question' comment.id %}"> 삭제</a>
    {% endif %}
  </div>
  {% endfor %}
</div>
{% endif %}

<div>
  <a href="{% url 'pybo:comment_create_question' question.id %}" class="small"><small>댓글 추가 ....</small></a>
</div>
<!-- 질문 댓글 End -->

practice2/templates/pybo/question_detail.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 
'bootstrap.min.css' %}"
/>

<!-- /<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" /> -->

<div class="container my-3">
  <!-- 사용자오류 표시 -->
  {% if messages %}
  <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
    <strong>{{message.tags}}</strong>
    <ul>
      <li>{{message.message}}</li>
    </ul>
    {% endfor %}
  </div>
  {% endif %}
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">{{ question.content }}</div>
      <div class="d-flex justify-content-end">
        {% if question.modify_date %}
        <div class="badge badge-light p-2 text-left mx-3">
          <div class="mb-2">modified at</div>
          <div>{{ question.modify_date }}</div>
        </div>
        {% endif %}

        <div class="badge badge-light p-2 text-left">
          <div class="mb-2">{{ question.author.username }}</div>
          <div>{{ question.create_date }}</div>
        </div>
      </div>
      {% if request.user == question.author %}
      <div class="my-3">
        <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-url="{% url 'pybo:question_delete' question.id %}">삭제</a>
      </div>
      {% endif %} {% include 'pybo/comment_list.html' %}
    </div>
  </div>
  {% include 'pybo/answer_list.html' %}

  <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
  {% for answer in question.answer_set.all %}
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">{{ answer.content }}</div>
      <div class="d-flex justify-content-end">
        {% if answer.modify_date %}
        <div class="badge badge-light p-2 text-left mx-3">
          <div class="mb-2">modified at</div>
          <div>{{ answer.modify_date }}</div>
        </div>
        {% endif %}
        <div class="badge badge-light p-2 text-left">
          <div class="mb-2">{{ answer.author.username }}</div>
          <div>{{ answer.create_date }}</div>
        </div>
      </div>
      {% if request.user == answer.author %}
      <div class="my-3">
        <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-url="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
      </div>
      {% endif %} {% if answer.comment_set.count > 0 %}
      <div class="mt-3">
        {% for comment in answer.comment_set.all %}
        <div class="comment py-2 text-muted">
          <span style="white-space: pre-line"> {{ comment.content }}</span>
          <span>
            - {{ comment.author }}, {{ comment.create_date }} {% if comment.modify_date %} (수정:{{ comment.modify_date }}) {% endif %}
          </span>
          {% if request.user == comment.author %}
          <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>,
          <a href="#" class="small delete" data-url="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
          {% endif %}
        </div>
        {% endfor %}
      </div>
      {% endif %}
      <div>
        <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small"><small>댓글 추가 ....</small></a>
      </div>
    </div>
  </div>
  {% endfor %}
  <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
    {% csrf_token %} {% include 'error/form_error.html' %}
    <div class="form-group">
      <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-primary" />
  </form>
</div>
{% endblock %}

<!-- 스크립트 블럭 -->
{% block script %}
<script type="text/javascript">
  $(document).ready(function () {
    $(".delete").on("click", function () {
      if (confirm("정말로 삭제하시겠습니까?")) {
        location.href = $(this).data("url");
      }
    });
  });
</script>
{% endblock %}

practice2/templates/pybo/question_form.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %} {% include 'error/form_error.html' %}

    <div class="form-group">
      <label for="subject">제목</label>
      <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}" />
    </div>
    <div class="form-group">
      <label for="content">내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">{{form.content.value|default_if_none:''}}</textarea>
    </div>

    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

practice2/templates/pybo/question_list.html
{% extends 'base.html' %}
<!-- 커스텀 필터 적용 -->
{% load pybo_filter%} {% block content %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<div class="container my-3">
  <table class="table table-hover">
    <thead>
      <tr class="thead-dark">
        <th>번호</th>
        <th>제목</th>
        <th>글쓴이</th>
        <th style="width: 120px">작성일시</th>
      </tr>
    </thead>
    <tbody>
      {% if question_list %} {% for question in question_list %}
      <tr>
        <!-- 1부터 10까지 -->
        <!-- <td>{{ forloop.counter }}</td> -->
        <!-- 번호 = 전체건수 -시작인덱스 -현재인덱스 +1  -->
        <!-- <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td> -->
        <!-- 생성된 id 번호  -->
        <td>{{question.id}}</td>
        <td>
          <a href="{% url 'pybo:detail' question.id %}"> {{ question.subject }}</a>
          {% if question.answer_set.count > 0 %}
          <span class="badge badge-pill badge-primary"> {{ question.answer_set.count }}</span>
          {% endif %}
        </td>
        <td>{{question.author.username}}</td>
        <td>{{ question.create_date|date:'Y-m-d' }}</td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td colspan="3">질문이 없습니다.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  {% include 'pagination.html' with page_object=question_list %}

  <a href="{% url 'pybo:question_create' %}" class="btn btn-primary"> 질문 등록하기</a>

  <div class="text-right float-right">총: {{question_list.paginator.count}} 건</div>
</div>
{% endblock %}