practice2/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'
urlpatterns = [

path('login/',auth_views.LoginView.as_view(template_name = 'common/login.html'), name='login' ),
path('logout/', auth_views.LogoutView.as_view(), name='logout'),
path('signup/', views.signup, name = 'signup')
]

practice2/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/',include('common.urls')),
    path('', base_views.index,name='index'),
]

practice2/pybo/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views, comment_views



app_name = 'pybo'

urlpatterns=[
  # base
  path('', base_views.index,name='index'),
  path('<int:question_id>/',base_views.detail,name='detail'),

# question
  path('question/create/', question_views.question_create, name='question_create'),
  path('question/modify/<int:question_id>/',question_views.question_modify, name='question_modify'),
  path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
  
# answer
  path('answer/create/<int:question_id>/',answer_views.answer_create, name='answer_create'),
  path('answer/modify/<int:answer_id>/', answer_views.answer_modify,   name='answer_modify'),
  path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

# comment
  path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
  path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
  path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
  path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
  path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
  path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),



]

practice2/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question


def index(request):
  """
  pybo 목록 출력
  """

  page = request.GET.get('page','1') 
  question_list = Question.objects.order_by('-create_date')
  paginator = Paginator(question_list,10)
  page_obj = paginator.get_page(page)
  context = {'question_list':page_obj}

  # question_list = Question.objects.order_by('-create_date')
  # context= {'question_list':question_list}

  return render(request, 'pybo/question_list.html',context)

def detail(request, question_id):
  """
  pybo 내용 출력
  """
  # question=Question.objects.get(id=question_id)
  question=get_object_or_404(Question,pk=question_id)
  context = {'question':question}
  return render(request,'pybo/question_detail.html',context)

practice2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" />
    <!-- fontawesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesomefree/css/all.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, pybo!</title>
  </head>

  <body>
    <div class="container">
      <div class="jumbotron mb-0 rounded-0">
        <h1>pybo를 통한 Django 학습</h1>
        <p class="lead">Django와 Bootstrap을 이용한 사이트 구축 학습</p>
      </div>
      {% include 'navbar.html' %}
      <!-- 기본 템플릿 안에 삽입될 내용 Start -->
      {% block content %}{% endblock %}
      <!-- 기본 템플릿 안에 삽입될 내용 End -->
    </div>
    <!-- jquery -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- bootstrap -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <!-- 스크립트 블럭 -->
    {% block script %} {% endblock %}
  </body>
</html>

practice2/templates/navbar.html
{% load static %} {% static "" as baseUrl %}

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom sticky-top">
  <a class="navbar-brand" href="{% url 'pybo:index' %}"><i class="fas fa-home"></i> Pybo</a>
  <button
    class="navbar-toggler ml-auto"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'common:logout' %}">
          <img src="{{baseUrl}}images/avatas/{{user.username}}.png" class="avata-sm rounded" /> {{ user.username }} (로그아웃)</a
        >
        {% else %}
        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>

practice2/templates/pagination.html
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
  <!-- 이전페이지 -->
  {% if page_object.has_previous %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_object.previous_page_number }}">이전</a>
  </li>
  {% else %}
  <li class="page-item disabled">
    <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> 이전</a>
  </li>
  {% endif %}
  <!-- 페이지리스트 -->
  {% for page_number in page_object.paginator.page_range %}
  <!--앞뒤 5개씩-->
  {% if page_number >= page_object.number|add:-5 and page_object.number|add:5 >= page_number %}
  <!-- 페이지넘버체크 -->
  {% if page_number == page_object.number %}
  <li class="page-item active" aria-current="page">
    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
  </li>
  {% else %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
  </li>
  {% endif %} {% endif %} {% endfor %}
  <!-- 다음페이지 -->
  {% if page_object.has_next %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_object.next_page_number }}">다음</a>
  </li>
  {% else %}
  <li class="page-item disabled">
    <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> 다음</a>
  </li>
  {% endif %}
</ul>
<!-- 페이징처리 끝 -->